[package]

name = "piston_window"
version = "0.102.0"
authors = ["bvssvni <bvssvni@gmail.com>"]
keywords = ["window", "piston"]
description = "The official Piston window wrapper for the Piston game engine"
license = "MIT"
readme = "README.md"
repository = "https://github.com/pistondevelopers/piston_window.git"
homepage = "https://github.com/pistondevelopers/piston_window"
documentation = "https://docs.rs/piston_window"

[lib]

path = "src/lib.rs"
name = "piston_window"


[dependencies]
gfx = "0.17.1"
gfx_device_gl = "0.15.0"
piston = "0.49.0"
piston2d-gfx_graphics = "0.63.0"
piston2d-graphics = "0.33.0"
piston-texture = "0.6.0"
shader_version = "0.6.0"


pistoncore-glutin_window = {version = "0.63.0", optional = true}

[features]
default = ["glutin"]
glutin = ["pistoncore-glutin_window"]
